# frozen_string_literal: true

source "https://rubygems.org"

gemspec

# Dev depndencies
gem "rake", "~> 13.0"
gem "minitest", "~> 5.16"
gem "byebug", "~> 11.1"

# Tools dependencies, should probably be into gemspec but i wont release the gem so whatever
gem "ox", "~> 2.14"
gem "rubyzip", "~> 2.3"
gem "bigdecimal", "~> 3.1"
